name: 'Main CI Build'
on: [push, pull_request_target]

jobs:
  test:
    name: Test Build (Python ${{ matrix.python }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python: ['3.7', '3.8', '3.9', '3.9-dev', '3.10-dev']
        os: ['ubuntu-latest', 'macos-latest']
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2.3.4
        with:
          submodules: true
      - name: Setup Python ${{ matrix.python }} on ${{ matrix.os }}
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ matrix.python }} 
      - name: Install packages
        run: |
          python -m pip install --upgrade pip wheel flake8
      - name: Show python version and show package
        run: |
          python --version
          sopel --version
          pip show MirahezeBot-Plugins
      - name: Run tests
        run: |
          flake8 .
